package framework.steps;

import com.fasterxml.jackson.databind.ObjectMapper;
import database.WrappedEntityManager;
import database.models.Users;
import framework.models.requests.LoginRequest;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import org.springframework.beans.factory.annotation.Autowired;
import utils.ScenarioContext;

import java.util.List;

import static utils.constants.ScenarioContextConstants.REGISTER_DATA;
import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

public class DbSteps {

  private WrappedEntityManager wrappedEntityManager;
  private ScenarioContext scenarioContext;

  @Autowired
  public DbSteps(WrappedEntityManager wrappedEntityManager, ObjectMapper mapper, ScenarioContext context) {
    this.wrappedEntityManager = wrappedEntityManager;
    this.scenarioContext = context;
  }

  @Then("verify user with username from context is present in db table users")
  public void verifyUserWithId() {
    LoginRequest response = scenarioContext.get(REGISTER_DATA);
    String username = response.getUsername();
    List<Users> users = wrappedEntityManager.findAllByFieldName("username", username, Users.class);
    assertThat(users.size()).isEqualTo(1);
  }

  @Then("verify user with username from context is not present in db table users")
  public void verifyUserWithIdNotPresent() {
    LoginRequest response = scenarioContext.get(REGISTER_DATA);
    String username = response.getUsername();
    List<Users> users = wrappedEntityManager.findAllByFieldName("username", username, Users.class);
    assertThat(users.size()).isEqualTo(0);
  }

  @When("all users generated by framework are deleted")
  public void deleteAllUsersFromFramework() {
    wrappedEntityManager.performNativeQuery("DELETE FROM USERS WHERE USERNAME LIKE '%-TST079'");
  }



}
